config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :cat_entries

  resources :users, except: [:show]

  resource :sessions, only: [:new, :create, :destroy]
end

app/models/cat_entry.rb
class CatEntry
  include Api::Resource

  attr_accessor :id

  attr_accessor :breed

  attr_accessor :photo_url

  attr_accessor :longitude

  attr_accessor :latitude

  attr_accessor :color

  attr_accessor :event_date

  attr_accessor :entry_type

  attr_accessor :contact_email

  attr_accessor :contact_phone

  attr_accessor :resolved

  attr_accessor :chip

  attr_accessor :user

  def attributes
    {breed: nil,
     photo_url: nil,
     longitude: nil,
     latitude: nil,
     color: nil,
     event_date: nil,
     entry_type: nil,
     contact_email: nil,
     contact_phone: nil,
     resolved: nil,
     chip: nil}
  end

  class << self
    def all
      execute(:get, '/api/cat_entries').map { |ce| CatEntry.new(ce) }
    end

    def find(id)
      CatEntry.new(execute(:get, "/api/cat_entries/#{id}"))
    end
  end

  def save
    if id.present?
      self.class.execute(:put, "/api/cat_entries/#{id}", cat_entry: self.serializable_hash)
    else
      response = self.class.execute(:post, '/api/cat_entries', cat_entry: self.serializable_hash)
      self.id = response[:id]
    end

    true
  rescue RestClient::UnprocessableEntity => exception
    add_errors_to_resource(exception, self)
    false
  end

  def persisted?
    id.present?
  end

  def user_id
    user.presence[:id]
  end

  def destroy
    self.class.execute(:delete, "/api/cat_entries/#{id}")
  end
end

app/controllers/cat_entries_controller.rb
class CatEntriesController < ApplicationController
  # Load the cat entry
  before_filter :load_cat_entry, only: [:show, :edit, :update, :destroy]

  # GET /cat_entries
  def index
    authorize! :read, CatEntry

    @cat_entries = CatEntry.all
  end

  # Get /cat_entries/:id
  def show
    authorize! :read, CatEntry
  end

  # GET /cat_entries/new
  def new
    authorize! :create, CatEntry
    entry_type = params[:type] if %w(lost found).include?(params[:type])
    @cat_entry = CatEntry.new(entry_type: entry_type, contact_email: session[:user_information][:email])
  end

  # POST /cat_entries
  def create
    authorize! :create, CatEntry

    @cat_entry = CatEntry.new(params[:cat_entry])

    if @cat_entry.save
      redirect_to cat_entry_path(id: @cat_entry.id)
    else
      render :new
    end
  end

  # GET /cat_entries/:id/edit
  def edit
    authorize! :update, @cat_entry
  end

  # PUT/PATCH /cat_entries/:id
  def update
    authorize! :update, @cat_entry

    @cat_entry.attributes= params[:cat_entry]

    if @cat_entry.save
      redirect_to cat_entry_path(id: @cat_entry.id)
    else
      render :new
    end
  end

  # DELETE /cat_entries/:id
  def destroy
    authorize! :destroy, @cat_entry

    @cat_entry.destroy
    redirect_to cat_entries_path
  end

  private

  # Retrieves the cat entry with the given id
  def load_cat_entry
    @cat_entry = CatEntry.find(params[:id])
  end
end

app/helpers/cat_entries_helper.rb
module CatEntriesHelper
  def entry_types
    %w(lost found)
  end
end

app/views/cat_entries/_form.html.erb
<%= simple_form_for cat_entry do |form| %>
    <div class="row">
        <div class="small-12 columns">
            <label>
                Lost or Found?
                <%= form.input :entry_type, :collection => entry_types, :label => false %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :breed, :error_html => { :class => 'error' }, :placeholder => 'Enter the cat\'s breed' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :color, :error_html => { :class => 'error' }, :placeholder => 'Enter the cat\'s color' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :event_date, :input_html => { :class => 'datepicker' }, :error_html => { :class => 'error' }, :placeholder => 'When did you find/lost the cat?' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :contact_email, :error_html => { :class => 'error' }, :placeholder => 'Enter the a contact email' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :contact_phone, :error_html => { :class => 'error' }, :placeholder => 'Enter a contact phone' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :chip, :error_html => { :class => 'error' }, :placeholder => 'Does the cat have a chip? Here goes the number.' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :photo_url, :error_html => { :class => 'error' }, :placeholder => 'Enter a URL of a cat\'s image' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :longitude, :error_html => { :class => 'error' }, :placeholder => 'Enter an approximate longitude of the area you found/lost the cat' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <label>
                <%= form.input :latitude, :error_html => { :class => 'error' }, :placeholder => 'Enter an approximate latitude of the area you found/lost the cat' %>
            </label>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <%= form.submit 'Save', :class => 'button expand' %>
        </div>
    </div>
<% end %>

app/views/cat_entries/edit.html.erb
<div class="row">
    <div class="small-12 medium-6 medium-offset-3 columns">

        <h1>Edit Cat Entry</h1>
        <h4 class="subheader">
            <small>Use this form to update the entry's properties.</small>
        </h4>

        <%= render :partial => 'form', :locals => {:cat_entry => @cat_entry} %>
    </div>
</div>

app/views/cat_entries/index.html.erb
<h1>Cat Entries</h1>
<h4 class="subheader"><small>Browse for cat entries. Press the 'details' link for more information for each entry.</small></h4>

<% if @cat_entries.blank? %>
    <div class="alert-box">
        Currenty all cats are with their owners!
    </div>
<% else %>
    <ul class="cat-list small-block-grid-1 medium-block-grid-2 large-block-grid-3">
        <% @cat_entries.each do |cat_entry| %>
            <li>
                <div class="cat-details-container">
                    <table cellspacing="0" cellpadding="0">
                        <tr>
                            <td class="cat-list-photo" style="background-image: url(<%= cat_entry.photo_url %>)"></td>

                            <td>
                                <div class="cat-list-details">
                                    <div class="row">
                                        <div class="small-4 columns">
                                            <span class="label radius <%= cat_entry.entry_type == 'lost' ? 'alert' : 'warning' %>"><%= cat_entry.entry_type.capitalize %></span>
                                        </div>
                                        <div class="small-8 columns">
                                            <%= cat_entry.event_date %>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="small-4 columns">
                                            <strong>Breed:</strong>
                                        </div>
                                        <div class="small-8 columns">
                                            <%= cat_entry.breed %>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="small-4 columns">
                                            <strong>Color:</strong>
                                        </div>
                                        <div class="small-8 columns">
                                            <%= cat_entry.color %>
                                        </div>
                                    </div>

                                    <div class="text-right">
                                        <% if can? :update, cat_entry %>
                                            <%= link_to edit_cat_entry_path(cat_entry.id) do %>
                                                <i class="fa fa-edit"></i>
                                                <span>edit</span>
                                            <% end %>
                                        <% end %>

                                        <% if can? :destroy, cat_entry %>
                                            <%= link_to cat_entry_path(cat_entry.id), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this entry?'} do %>
                                                <i class="fa fa-remove"></i>
                                                <span>delete</span>
                                            <% end %>
                                        <% end %>

                                        <%= link_to cat_entry_path(:id => cat_entry.id) do %>
                                            <i class="fa fa-eye"></i>
                                            <span>details</span>
                                        <% end %>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/cat_entries/new.html.erb
<div class="row">
    <div class="small-12 medium-6 medium-offset-3 columns">
        <h1>New Cat Entry</h1>
        <h4 class="subheader"><small>Use this form to create a new entry.</small></h4>

        <%= render :partial => 'form', :locals => { :cat_entry => @cat_entry } %>
    </div>
</div>

app/views/cat_entries/show.html.erb
<div class="row cat-list-details">
    <div class="small-12 medium-6 medium-offset-3 columns">
            <h1>Cat entry</h1>
            <h4 class="subheader"><small>View details of the entry.</small></h4>

            <div class="row">
                <div class="small-12 columns">
                    <div class="alert-box <%= @cat_entry.entry_type == 'lost' ? 'alert' : 'warning' %>">
                        <%= @cat_entry.entry_type.capitalize %>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="small-6 columns">
                    <strong>When</strong>
                </div>
                <div class="small-6 columns">
                    <%= @cat_entry.event_date %>
                </div>
            </div>

            <div class="row">
                <div class="small-6 columns">
                    <strong>Color:</strong>
                </div>
                <div class="small-6 columns">
                    <%= @cat_entry.color %>
                </div>
            </div>

            <div class="row">
                <div class="small-6 columns">
                    <strong>Breed:</strong>
                </div>
                <div class="small-6 columns">
                    <%= @cat_entry.breed %>
                </div>
            </div>

            <div class="row">
                <div class="small-6 columns">
                    <strong>Chip:</strong>
                </div>
                <div class="small-6 columns">
                    <%= @cat_entry.chip %>
                </div>
            </div>

            <div class="row">
                <div class="small-6 columns">
                    <strong>Contact email:</strong>
                </div>
                <div class="small-6 columns">
                    <%= @cat_entry.contact_email %>
                </div>
            </div>

            <div class="row">
                <div class="small-6 columns">
                    <strong>Contact phone:</strong>
                </div>
                <div class="small-6 columns">
                    <%= @cat_entry.contact_phone %>
                </div>
            </div>

            <div class="actions text-center">
                <img src="<%= @cat_entry.photo_url %>"/>

                <div class="area-container">
                    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=470x300&sensor=true&zoom=10&markers=#{@cat_entry.latitude}%2C#{@cat_entry.longitude}" %>
                </div>
            </div>


        <div class="row actions">
            <% if can? :update, @cat_entry %>
                <div class="small-12 medium-6 columns">
                    <%= link_to edit_cat_entry_path(@cat_entry.id), :class => 'button expand' do %>
                        <i class="fa fa-edit"></i>
                        <span>edit</span>
                    <% end %>
                </div>
            <% end %>

            <% if can? :destroy, @cat_entry %>
                <div class="small-12 medium-6 columns">
                    <%= link_to cat_entry_path(@cat_entry.id), :method => :delete, :class => 'button expand' do %>
                        <i class="fa fa-remove"></i>
                        <span>delete</span>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>